services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - "5000:5000"
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
    ports:
      - "5432:5432"
